<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>db1be164-02ef-4718-9e33-dac3ed1fab44</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContentSubmission.Application\ContentSubmission.Application.csproj" />
    <ProjectReference Include="..\ContentSubmission.Domain\ContentSubmission.Domain.csproj" />
    <ProjectReference Include="..\ContentSubmission.Infrastructure\ContentSubmission.Infrastructure.csproj" />
  </ItemGroup>

</Project>
